config/routes.rb
Rails.application.routes.draw do
  resources :samples
  resources :users
  resources :posts
  resources :photos
  get 'home/index'
  get '/' => "home#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/sample.rb
class Sample < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts = Post.all
	end
	
   	def show
	@post = Post.find(params[:id])
	end
 	

	def new
	@post = Post.new
	end

	def create
	    @post = Post.new(post_params)

			respond_to do |format|
		      if @post.save
		        format.html { redirect_to @post, notice: 'Post was successfully created.' }
		        format.json { render :show, status: :created, location: @post }
		      else
		        format.html { render :new }
		        format.json { render json: @post.errors, status: :unprocessable_entity }
		      end
	    	end
	end

	def update
		respond_to do |format|
	      if @post.update(post_params)
	        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
	        format.json { render :show, status: :ok, location: @post }
	      else
	        format.html { render :edit }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
		puts "PARAMS ARE" + params.inspect
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to "/posts"
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
    
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:fname, :lname, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController   
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
  @users = User.all  
  end   

  def update  
  respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end 
  end

  def create
  	@user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end 

  def new
  	@user = User.new
  end

  def destroy
  		puts "PARAMS ARE" + params.inspect
		@user = User.find(params[:id])
		@user.destroy
		redirect_to "/users"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/home/index.html.erb
<h1>Darius Jones Railsblog</h1>
<p>Welcome to the homepage!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DjRailsblog</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<p>You can place a photo here</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>This is the list of all the post</h1>

<table border = "1" >

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <p><td><%= post.content %></td></p>
        <td><a href="/posts/<%= post.id%>">Show</a></td>
        <td><%= link_to "Edit", edit_post_path(post)%></td>
        <td><%= link_to "Delete Post", post_path(post.id), method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Posts', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
	<%= @user.inspect %>
</p>
<p>
   <%= @post.content %>
</p>
<%= link_to 'Back', posts_path %>

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Samples</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= sample.fname %></td>
        <td><%= sample.lname %></td>
        <td><%= sample.email %></td>
        <td><%= link_to 'Show', sample %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%= button_to 'Destroy Account', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @sample.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @sample.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sample.email %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Users</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>This is the list of Users in the Database</h1>
 <br>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td> 
        <td><%= link_to 'Destroy User', user, method: :delete %></td>
        <br>
      </tr>
    <% end %>
  </tbody>
<br>
  <%= link_to 'Create User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>